export { equal, equal as isEqual } from './equal'
export { falsy, falsy as isFalsy } from './falsy'
export { falsyOr } from './falsyOr'
export { ifThis } from './ifThis'
export { isFalse } from './isFalse'
export { isFn } from './isFn'
export { isNumber } from './isNumber'
export { isNumbers } from './isNumbers'
export { isObject } from './isObject'
export { isRealNumber } from './isRealNumber'
export { isRealPoint } from './isRealPoint'
export { isString } from './isString'
export { isTrue } from './isTrue'
export { notEqual, notEqual as isNotEqual } from './notEqual'
export { notNullish, notNullish as isNotNullish } from './notNullish'
export { notNullishOr } from './notNullishOr'
export {
  notStrictEqual,
  notStrictEqual as isNotStrictEqual,
} from './notStrictEqual'
export { nullish, nullish as isNullish } from './nullish'
export { nullishOr } from './nullishOr'
export { strictEqual, strictEqual as isStrictEqual } from './strictEqual'
export { truthy, truthy as isTruthy } from './truthy'
export { truthyOr } from './truthyOr'
